def function():
    """
    decorator function that returns a list of the function .
    AI-generated by Ponicode.
    """
    return nothing

ok

class Test():
    def add(a, b):
        return a + b

def greetings():
    print("Hello world")

def greetings():
    print('Hello world')
    